### ISSUE TITLE
No dependencies release

### ISSUE THREAD

**Issue by elfwine** [spyhunter99/installcert#21]
Is it possible to have a no/less dependencies release?
It would be great if there's a no-dependencies release and just the basic StarttlsHandler or make Start TLS as an option.

Thanks,

**Comment by spyhunter99** [comment]
do you mean as a jar without dependencies or is this more of a build system issue, i.e. importing the project using maven or gradle but exclude any dependencies?

**Comment by spyhunter99** [comment]
ok i have a solution for removing the postgres dependency
