### ISSUE TITLE
 Support for JDK17. Remove use of 'sun.security.'

### ISSUE THREAD

**Issue by breunouddanedeu** [spyhunter99/installcert#81]
I have an issue using JRE 17, `sun.security` classes are no longer accessible.

Can you remove dependency to these classes ?

For information, it is possible to work around this issue by adding `--add-exports=java.base/sun.security.validator=ALL-UNNAMED --add-exports=java.base/sun.security.provider.certpath=ALL-UNNAMED` to java arguments.

**Comment by spyhunter99** [comment]
hmm what's the alternative classes in jdk17+? i think this is all that's used
````
import sun.security.provider.certpath.SunCertPathBuilderException;
import sun.security.validator.ValidatorException;
````
